#!/bin/sh

[[() {
  local ret
  local j
  [ ! "$4" = "]]" ] && return 1
  case "$1" in
    -a|-e)	[ -e "$2" ] || ret=1 ;;
    -b|-c|-d|-f|-g|-h|-k|-n|-p|r|-s|-t|-u|-w|-x|-z|-L|-G|-S|-O)
    		[ "$1" "$2" ] || ret=1 ;;
    -N)	[ -e "$2" -a $(stat -f '%m' "$2") -gt $(stat -f '%a' "$2") ] || ret=1 ;;
    -o)	ret=70 ;;
    -v)	[ -n "$2" ] || ret=1 ;;
    -R)	ret=1 ;;
    -*) ret=64 ;;
  esac
  case "$2" in
    -ef|-nt|-ot) [ "$1" "$2" "$3" ] || ret=1 ;;
    =|==) [ "$1" != "$3" ] && ret=1 ;;
    !=) [ "$1" = "$3" ] && ret=1 ;;
    \<|\>) expr "${1}${2}" : '.*[^0-9]' >/dev/null && return 64 ;&
    \<) [ ! "$1" -lt "$3"] && ret=1 ;;
    \>) [ ! "$1" -gt "$3"] && ret=1 ;;
    -eq|-ne|-lt|-le|-gt|-ge) [ "$1" "$2" "$3" ] || ret=1 ;;
    ~)
       j="${3#.}"
       if [ "${3%%$j}" = "^" ]; then
         re="${3%%$j}"
       else
         re=".*$3"
       fi
       expr "$1" : "$re" >/dev/null || ret=1
       ;;
    *) ret=70 ;;
  esac
  return ${ret:-0}
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]] || [[ -z "${BASH_SOURCE[0]}" ]]; then
    [[ "$@"
fi

